#!/bin/bash
# backup daily
st=${1:-$(($RANDOM%21600))}
echo "sleep $st secends from $(date)"
sleep $st
RSYNC_PASSWORD='backupATvph0t0s' rsync   -avz  /etc piprsync@10.3.16.18::pushbackup/$(hostname -I|head -n 1|awk '{print $1}')/
