# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-13 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ngxconf',
        ),
    ]
